language: c
os:
 - linux
 - osx
compiler:
 - gcc
 - clang
addons:
  apt:
    packages:
     - libjansson-dev
before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update         ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install jansson; fi
script: make
